name: javascript
on: pull_request
jobs:
    build:
      name: eslint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1

        - uses: actions/setup-node@v1
          with:
            node-version: '10.16.3'

        - name: yarn install
          run: yarn install --frozen-lockfile

        - name: eslint
          uses: getsentry/action-eslint-fix@08ae3b9
          with:
            myToken: ${{ secrets.GITHUB_TOKEN }}
            job-name: eslint
